baseurl = "https://abduwaly.github.io/ArsayCode"
languageCode = "en"
title = "ArsayCode"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/abduwaly\">Abduwaly</a> 2019"
disqusShortname = "Abduwaly's Place"
publishdir = "docs"

[params]

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "../about.html"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/abduwaly"
  fa_icon = "fab fa-github"

